feat(/): เพิ่ม ตำบล (สำหรับจังหวัดอื่นๆ) /แขวง (สำหรับกรุงเทพ) ไว้ในลิสต์ตัวเลือก
wevisdemo/they-work-for-us pull request #83
Opened 2023-04-22 18:38 UTC by bothonachiz

#78 
- เพิ่ม election zone (ปี 62)
- เพิ่ม postcode (ปี62)
- แก้ไข locationBuilder.js เพื่อสร้าง location options จาก ไฟล์ข้างต้น
- Improvement Autocomplete ให้รองรับ Options 7000+ รายการ

2023-05-03 16:05 UTC, Th1nkK1D requested changes
ขอโทษที่มาเช็คช้าครับบบ วันหลังเปิด PR แล้วกดชื่อผมตรง reviewer ใน PR ได้เลยนะครับ บางทีไม่ได้มากดเช็คบ่อย

โดยรวมเท่าที่ test function ใช้ได้เลยฮะ กราบ มีฝากแก้ visual นิดๆ หน่อยๆ

1. placeholder แก้เป็น แขวง/ตำบล
2. ตอนนี้แค่ focus input มันก็โชว์ dropdown เลย รอพิมพ์อย่างน้อย 1 ตัวอักษรก่อนดีกว่า
3. ผมลองเลือกไปแล้วเขตนึง พอกลับมาใหม่เขตที่เลือกมันค้างอยู่ใน input ถ้าเลือกแล้ว pop up เปิดแล้ว clear input ดีกว่าครับ
![image](https://user-images.githubusercontent.com/8860448/235974202-87034947-1408-4f19-9a6a-bcf5326db122.png)

นอกจากนั้นก็มีแค่ feedback code styling นิหน่อยครับ

2023-05-04 09:49 UTC, bothonachiz commented
Update เพิ่มเติม ตาม Comment ให้เรียบร้อยแล้วฮะ @Th1nkK1D

2023-05-04 13:28 UTC, Th1nkK1D reviewed
งามครับบบ เท่าที่ลองเทสคือใช้ได้เยี่ยม ผมฝากแก้อันสุดท้าย

2023-05-04 13:35 UTC, bothonachiz commented on src/pages/index.js
> +          setIsZoneDialog={(e) => onZoneDialogClose(e)}
เรียบร้อยครับ 🫡

2023-05-04 13:45 UTC, Th1nkK1D approved these changes
LGTM! Thank you for the contribution krub

2023-05-04 13:46 UTC, merged